jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
      - run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=. -e 'using Pkg; Pkg.test()'
